rules:
  prototypeNamePrefix:
    class: 'Vette\Neos\CodeStyle\Rules\Neos\PrototypeNamePrefixRule'
    severity: warning
    options:
      ignorePackages: ['Neos.Neos']
      validPrefixes: ['Content', 'Document', 'Component', 'Helper', 'Presentation', 'Integration']
  onlyIncludesInRootFile:
    class: 'Vette\Neos\CodeStyle\Rules\Neos\OnlyIncludesInRootRule'
    severity: info
  onePrototypePerFile:
    class: 'Vette\Neos\CodeStyle\Rules\Neos\OnePrototypePerFileRule'
  fluidTemplate:
    class: 'Vette\Neos\CodeStyle\Rules\Neos\FluidTemplateRule'
    severity: error
  emptyBlock:
    class: 'Vette\Neos\CodeStyle\Rules\Generic\EmptyBlockRule'
    severity: error
  operatorSpacing:
    class: 'Vette\Neos\CodeStyle\Rules\Generic\OperatorSpacingRule'
    severity: error
  blockSpacing:
    class: 'Vette\Neos\CodeStyle\Rules\Generic\BlockSpacingRule'
    severity: error
  eelSpacing:
    class: 'Vette\Neos\CodeStyle\Rules\Generic\EelSpacingRule'
    severity: error
  nodeProperties:
    class: 'Vette\Neos\CodeStyle\Rules\Neos\NodePropertiesRule'
    severity: error
  contextInFirstLevel:
    class: 'Vette\Neos\CodeStyle\Rules\Neos\ContextInFirstLevelRule'
    severity: warning
  ternaryOperator:
    class: 'Vette\Neos\CodeStyle\Rules\Neos\TernaryOperatorRule'
    severity: error

ruleSets:
  default:
    include: ['generic', 'neos']
  neos:
    rules:
      - 'fluidTemplate'
      - 'onePrototypePerFile'
      - 'onlyIncludesInRootFile'
      - 'prototypeNamePrefix'
      - 'nodeProperties'
      - 'contextInFirstLevel'
      - 'ternaryOperator'
  generic:
    rules: ['operatorSpacing','blockSpacing', 'emptyBlock', 'eelSpacing']

reports:
  console:
    class: Vette\Neos\CodeStyle\Reports\Console
  checkstyle:
    class: Vette\Neos\CodeStyle\Reports\Checkstyle

neosRoot:
files: []

defaultReport: console
defaultRuleSet: default
