name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.0"
          - "7.4"
          - "7.3"
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Run test suite
      run: composer run-script test
      
    - name: Cache tools installed with PHIVE
      uses: actions/cache@v2.1.2
      with:
          path: ${{ runner.temp }}/.phive
          key: php-${{ matrix.php-version }}-phive-${{ hashFiles('.phive/phars.xml') }}
          restore-keys: php-${{ matrix.php-version }}-phive-

    - name: Install PHIVE
      uses: szepeviktor/phive@v1
      with:
          home: ${{ runner.temp }}/.phive
          binPath: ${{ github.workspace }}/tools/phive

    - name: Install box
      run: ${{ github.workspace }}/tools/phive install humbug/box --force-accept-unsigned

     
